// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: temp.proto

package com.opera.core.systems.scope.protos;

public final class ConsoleLoggerProtos {
  private ConsoleLoggerProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ConsoleMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required uint32 windowID = 1;
    boolean hasWindowID();
    int getWindowID();
    
    // required uint32 time = 2;
    boolean hasTime();
    int getTime();
    
    // required string description = 3;
    boolean hasDescription();
    String getDescription();
    
    // optional string uri = 4;
    boolean hasUri();
    String getUri();
    
    // optional string context = 5;
    boolean hasContext();
    String getContext();
    
    // optional string source = 6;
    boolean hasSource();
    String getSource();
    
    // optional string severity = 7;
    boolean hasSeverity();
    String getSeverity();
  }
  public static final class ConsoleMessage extends
      com.google.protobuf.GeneratedMessage
      implements ConsoleMessageOrBuilder {
    // Use ConsoleMessage.newBuilder() to construct.
    private ConsoleMessage(Builder builder) {
      super(builder);
    }
    private ConsoleMessage(boolean noInit) {}
    
    private static final ConsoleMessage defaultInstance;
    public static ConsoleMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public ConsoleMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.opera.core.systems.scope.protos.ConsoleLoggerProtos.internal_static_scope_ConsoleMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.opera.core.systems.scope.protos.ConsoleLoggerProtos.internal_static_scope_ConsoleMessage_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required uint32 windowID = 1;
    public static final int WINDOWID_FIELD_NUMBER = 1;
    private int windowID_;
    public boolean hasWindowID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getWindowID() {
      return windowID_;
    }
    
    // required uint32 time = 2;
    public static final int TIME_FIELD_NUMBER = 2;
    private int time_;
    public boolean hasTime() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getTime() {
      return time_;
    }
    
    // required string description = 3;
    public static final int DESCRIPTION_FIELD_NUMBER = 3;
    private java.lang.Object description_;
    public boolean hasDescription() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          description_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string uri = 4;
    public static final int URI_FIELD_NUMBER = 4;
    private java.lang.Object uri_;
    public boolean hasUri() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getUri() {
      java.lang.Object ref = uri_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          uri_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUriBytes() {
      java.lang.Object ref = uri_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        uri_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string context = 5;
    public static final int CONTEXT_FIELD_NUMBER = 5;
    private java.lang.Object context_;
    public boolean hasContext() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getContext() {
      java.lang.Object ref = context_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          context_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getContextBytes() {
      java.lang.Object ref = context_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        context_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string source = 6;
    public static final int SOURCE_FIELD_NUMBER = 6;
    private java.lang.Object source_;
    public boolean hasSource() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public String getSource() {
      java.lang.Object ref = source_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          source_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getSourceBytes() {
      java.lang.Object ref = source_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        source_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string severity = 7;
    public static final int SEVERITY_FIELD_NUMBER = 7;
    private java.lang.Object severity_;
    public boolean hasSeverity() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public String getSeverity() {
      java.lang.Object ref = severity_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          severity_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getSeverityBytes() {
      java.lang.Object ref = severity_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        severity_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      windowID_ = 0;
      time_ = 0;
      description_ = "";
      uri_ = "";
      context_ = "";
      source_ = "";
      severity_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasWindowID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDescription()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, windowID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, time_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getDescriptionBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getUriBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getContextBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getSourceBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getSeverityBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, windowID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, time_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getDescriptionBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getUriBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getContextBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getSourceBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getSeverityBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.opera.core.systems.scope.protos.ConsoleLoggerProtos.ConsoleMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.opera.core.systems.scope.protos.ConsoleLoggerProtos.ConsoleMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.opera.core.systems.scope.protos.ConsoleLoggerProtos.ConsoleMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.opera.core.systems.scope.protos.ConsoleLoggerProtos.ConsoleMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.opera.core.systems.scope.protos.ConsoleLoggerProtos.ConsoleMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.opera.core.systems.scope.protos.ConsoleLoggerProtos.ConsoleMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.opera.core.systems.scope.protos.ConsoleLoggerProtos.ConsoleMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.opera.core.systems.scope.protos.ConsoleLoggerProtos.ConsoleMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.opera.core.systems.scope.protos.ConsoleLoggerProtos.ConsoleMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.opera.core.systems.scope.protos.ConsoleLoggerProtos.ConsoleMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.opera.core.systems.scope.protos.ConsoleLoggerProtos.ConsoleMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.opera.core.systems.scope.protos.ConsoleLoggerProtos.ConsoleMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.opera.core.systems.scope.protos.ConsoleLoggerProtos.internal_static_scope_ConsoleMessage_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.opera.core.systems.scope.protos.ConsoleLoggerProtos.internal_static_scope_ConsoleMessage_fieldAccessorTable;
      }
      
      // Construct using com.opera.core.systems.scope.protos.ConsoleLoggerProtos.ConsoleMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        windowID_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        time_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        description_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        uri_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        context_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        source_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        severity_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.opera.core.systems.scope.protos.ConsoleLoggerProtos.ConsoleMessage.getDescriptor();
      }
      
      public com.opera.core.systems.scope.protos.ConsoleLoggerProtos.ConsoleMessage getDefaultInstanceForType() {
        return com.opera.core.systems.scope.protos.ConsoleLoggerProtos.ConsoleMessage.getDefaultInstance();
      }
      
      public com.opera.core.systems.scope.protos.ConsoleLoggerProtos.ConsoleMessage build() {
        com.opera.core.systems.scope.protos.ConsoleLoggerProtos.ConsoleMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.opera.core.systems.scope.protos.ConsoleLoggerProtos.ConsoleMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.opera.core.systems.scope.protos.ConsoleLoggerProtos.ConsoleMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.opera.core.systems.scope.protos.ConsoleLoggerProtos.ConsoleMessage buildPartial() {
        com.opera.core.systems.scope.protos.ConsoleLoggerProtos.ConsoleMessage result = new com.opera.core.systems.scope.protos.ConsoleLoggerProtos.ConsoleMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.windowID_ = windowID_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.time_ = time_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.description_ = description_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.uri_ = uri_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.context_ = context_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.source_ = source_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.severity_ = severity_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.opera.core.systems.scope.protos.ConsoleLoggerProtos.ConsoleMessage) {
          return mergeFrom((com.opera.core.systems.scope.protos.ConsoleLoggerProtos.ConsoleMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.opera.core.systems.scope.protos.ConsoleLoggerProtos.ConsoleMessage other) {
        if (other == com.opera.core.systems.scope.protos.ConsoleLoggerProtos.ConsoleMessage.getDefaultInstance()) return this;
        if (other.hasWindowID()) {
          setWindowID(other.getWindowID());
        }
        if (other.hasTime()) {
          setTime(other.getTime());
        }
        if (other.hasDescription()) {
          setDescription(other.getDescription());
        }
        if (other.hasUri()) {
          setUri(other.getUri());
        }
        if (other.hasContext()) {
          setContext(other.getContext());
        }
        if (other.hasSource()) {
          setSource(other.getSource());
        }
        if (other.hasSeverity()) {
          setSeverity(other.getSeverity());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasWindowID()) {
          
          return false;
        }
        if (!hasTime()) {
          
          return false;
        }
        if (!hasDescription()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              windowID_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              time_ = input.readUInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              description_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              uri_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              context_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              source_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              severity_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required uint32 windowID = 1;
      private int windowID_ ;
      public boolean hasWindowID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getWindowID() {
        return windowID_;
      }
      public Builder setWindowID(int value) {
        bitField0_ |= 0x00000001;
        windowID_ = value;
        onChanged();
        return this;
      }
      public Builder clearWindowID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        windowID_ = 0;
        onChanged();
        return this;
      }
      
      // required uint32 time = 2;
      private int time_ ;
      public boolean hasTime() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getTime() {
        return time_;
      }
      public Builder setTime(int value) {
        bitField0_ |= 0x00000002;
        time_ = value;
        onChanged();
        return this;
      }
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        time_ = 0;
        onChanged();
        return this;
      }
      
      // required string description = 3;
      private java.lang.Object description_ = "";
      public boolean hasDescription() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDescription(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        description_ = value;
        onChanged();
        return this;
      }
      public Builder clearDescription() {
        bitField0_ = (bitField0_ & ~0x00000004);
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      void setDescription(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        description_ = value;
        onChanged();
      }
      
      // optional string uri = 4;
      private java.lang.Object uri_ = "";
      public boolean hasUri() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getUri() {
        java.lang.Object ref = uri_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          uri_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUri(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        uri_ = value;
        onChanged();
        return this;
      }
      public Builder clearUri() {
        bitField0_ = (bitField0_ & ~0x00000008);
        uri_ = getDefaultInstance().getUri();
        onChanged();
        return this;
      }
      void setUri(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        uri_ = value;
        onChanged();
      }
      
      // optional string context = 5;
      private java.lang.Object context_ = "";
      public boolean hasContext() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getContext() {
        java.lang.Object ref = context_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          context_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setContext(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        context_ = value;
        onChanged();
        return this;
      }
      public Builder clearContext() {
        bitField0_ = (bitField0_ & ~0x00000010);
        context_ = getDefaultInstance().getContext();
        onChanged();
        return this;
      }
      void setContext(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        context_ = value;
        onChanged();
      }
      
      // optional string source = 6;
      private java.lang.Object source_ = "";
      public boolean hasSource() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public String getSource() {
        java.lang.Object ref = source_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          source_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setSource(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        source_ = value;
        onChanged();
        return this;
      }
      public Builder clearSource() {
        bitField0_ = (bitField0_ & ~0x00000020);
        source_ = getDefaultInstance().getSource();
        onChanged();
        return this;
      }
      void setSource(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000020;
        source_ = value;
        onChanged();
      }
      
      // optional string severity = 7;
      private java.lang.Object severity_ = "";
      public boolean hasSeverity() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public String getSeverity() {
        java.lang.Object ref = severity_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          severity_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setSeverity(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        severity_ = value;
        onChanged();
        return this;
      }
      public Builder clearSeverity() {
        bitField0_ = (bitField0_ & ~0x00000040);
        severity_ = getDefaultInstance().getSeverity();
        onChanged();
        return this;
      }
      void setSeverity(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000040;
        severity_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:scope.ConsoleMessage)
    }
    
    static {
      defaultInstance = new ConsoleMessage(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:scope.ConsoleMessage)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_scope_ConsoleMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_scope_ConsoleMessage_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ntemp.proto\022\005scope\"\205\001\n\016ConsoleMessage\022\020" +
      "\n\010windowID\030\001 \002(\r\022\014\n\004time\030\002 \002(\r\022\023\n\013descri" +
      "ption\030\003 \002(\t\022\013\n\003uri\030\004 \001(\t\022\017\n\007context\030\005 \001(" +
      "\t\022\016\n\006source\030\006 \001(\t\022\020\n\010severity\030\007 \001(\tB<\n#c" +
      "om.opera.core.systems.scope.protosB\023Cons" +
      "oleLoggerProtosH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_scope_ConsoleMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_scope_ConsoleMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_scope_ConsoleMessage_descriptor,
              new java.lang.String[] { "WindowID", "Time", "Description", "Uri", "Context", "Source", "Severity", },
              com.opera.core.systems.scope.protos.ConsoleLoggerProtos.ConsoleMessage.class,
              com.opera.core.systems.scope.protos.ConsoleLoggerProtos.ConsoleMessage.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
