// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: temp.proto

package com.opera.core.systems.scope.protos;

public final class DesktopUtilsProtos {
  private DesktopUtilsProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface DesktopStringIDOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string enumText = 1;
    boolean hasEnumText();
    String getEnumText();
  }
  public static final class DesktopStringID extends
      com.google.protobuf.GeneratedMessage
      implements DesktopStringIDOrBuilder {
    // Use DesktopStringID.newBuilder() to construct.
    private DesktopStringID(Builder builder) {
      super(builder);
    }
    private DesktopStringID(boolean noInit) {}
    
    private static final DesktopStringID defaultInstance;
    public static DesktopStringID getDefaultInstance() {
      return defaultInstance;
    }
    
    public DesktopStringID getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.opera.core.systems.scope.protos.DesktopUtilsProtos.internal_static_scope_DesktopStringID_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.opera.core.systems.scope.protos.DesktopUtilsProtos.internal_static_scope_DesktopStringID_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string enumText = 1;
    public static final int ENUMTEXT_FIELD_NUMBER = 1;
    private java.lang.Object enumText_;
    public boolean hasEnumText() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getEnumText() {
      java.lang.Object ref = enumText_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          enumText_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getEnumTextBytes() {
      java.lang.Object ref = enumText_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        enumText_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      enumText_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasEnumText()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getEnumTextBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getEnumTextBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopStringID parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopStringID parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopStringID parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopStringID parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopStringID parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopStringID parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopStringID parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopStringID parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopStringID parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopStringID parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopStringID prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopStringIDOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.opera.core.systems.scope.protos.DesktopUtilsProtos.internal_static_scope_DesktopStringID_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.opera.core.systems.scope.protos.DesktopUtilsProtos.internal_static_scope_DesktopStringID_fieldAccessorTable;
      }
      
      // Construct using com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopStringID.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        enumText_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopStringID.getDescriptor();
      }
      
      public com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopStringID getDefaultInstanceForType() {
        return com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopStringID.getDefaultInstance();
      }
      
      public com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopStringID build() {
        com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopStringID result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopStringID buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopStringID result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopStringID buildPartial() {
        com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopStringID result = new com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopStringID(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.enumText_ = enumText_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopStringID) {
          return mergeFrom((com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopStringID)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopStringID other) {
        if (other == com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopStringID.getDefaultInstance()) return this;
        if (other.hasEnumText()) {
          setEnumText(other.getEnumText());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasEnumText()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              enumText_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string enumText = 1;
      private java.lang.Object enumText_ = "";
      public boolean hasEnumText() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getEnumText() {
        java.lang.Object ref = enumText_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          enumText_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setEnumText(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        enumText_ = value;
        onChanged();
        return this;
      }
      public Builder clearEnumText() {
        bitField0_ = (bitField0_ & ~0x00000001);
        enumText_ = getDefaultInstance().getEnumText();
        onChanged();
        return this;
      }
      void setEnumText(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        enumText_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:scope.DesktopStringID)
    }
    
    static {
      defaultInstance = new DesktopStringID(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:scope.DesktopStringID)
  }
  
  public interface DesktopStringTextOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string text = 1;
    boolean hasText();
    String getText();
  }
  public static final class DesktopStringText extends
      com.google.protobuf.GeneratedMessage
      implements DesktopStringTextOrBuilder {
    // Use DesktopStringText.newBuilder() to construct.
    private DesktopStringText(Builder builder) {
      super(builder);
    }
    private DesktopStringText(boolean noInit) {}
    
    private static final DesktopStringText defaultInstance;
    public static DesktopStringText getDefaultInstance() {
      return defaultInstance;
    }
    
    public DesktopStringText getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.opera.core.systems.scope.protos.DesktopUtilsProtos.internal_static_scope_DesktopStringText_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.opera.core.systems.scope.protos.DesktopUtilsProtos.internal_static_scope_DesktopStringText_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string text = 1;
    public static final int TEXT_FIELD_NUMBER = 1;
    private java.lang.Object text_;
    public boolean hasText() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getText() {
      java.lang.Object ref = text_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          text_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      text_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasText()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTextBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTextBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopStringText parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopStringText parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopStringText parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopStringText parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopStringText parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopStringText parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopStringText parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopStringText parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopStringText parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopStringText parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopStringText prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopStringTextOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.opera.core.systems.scope.protos.DesktopUtilsProtos.internal_static_scope_DesktopStringText_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.opera.core.systems.scope.protos.DesktopUtilsProtos.internal_static_scope_DesktopStringText_fieldAccessorTable;
      }
      
      // Construct using com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopStringText.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        text_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopStringText.getDescriptor();
      }
      
      public com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopStringText getDefaultInstanceForType() {
        return com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopStringText.getDefaultInstance();
      }
      
      public com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopStringText build() {
        com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopStringText result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopStringText buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopStringText result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopStringText buildPartial() {
        com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopStringText result = new com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopStringText(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.text_ = text_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopStringText) {
          return mergeFrom((com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopStringText)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopStringText other) {
        if (other == com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopStringText.getDefaultInstance()) return this;
        if (other.hasText()) {
          setText(other.getText());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasText()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              text_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string text = 1;
      private java.lang.Object text_ = "";
      public boolean hasText() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getText() {
        java.lang.Object ref = text_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          text_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setText(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        text_ = value;
        onChanged();
        return this;
      }
      public Builder clearText() {
        bitField0_ = (bitField0_ & ~0x00000001);
        text_ = getDefaultInstance().getText();
        onChanged();
        return this;
      }
      void setText(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        text_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:scope.DesktopStringText)
    }
    
    static {
      defaultInstance = new DesktopStringText(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:scope.DesktopStringText)
  }
  
  public interface DesktopPathOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string path = 1;
    boolean hasPath();
    String getPath();
  }
  public static final class DesktopPath extends
      com.google.protobuf.GeneratedMessage
      implements DesktopPathOrBuilder {
    // Use DesktopPath.newBuilder() to construct.
    private DesktopPath(Builder builder) {
      super(builder);
    }
    private DesktopPath(boolean noInit) {}
    
    private static final DesktopPath defaultInstance;
    public static DesktopPath getDefaultInstance() {
      return defaultInstance;
    }
    
    public DesktopPath getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.opera.core.systems.scope.protos.DesktopUtilsProtos.internal_static_scope_DesktopPath_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.opera.core.systems.scope.protos.DesktopUtilsProtos.internal_static_scope_DesktopPath_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string path = 1;
    public static final int PATH_FIELD_NUMBER = 1;
    private java.lang.Object path_;
    public boolean hasPath() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getPath() {
      java.lang.Object ref = path_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          path_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPathBytes() {
      java.lang.Object ref = path_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        path_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      path_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasPath()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getPathBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getPathBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopPath parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopPath parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopPath parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopPath parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopPath parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopPath parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopPath parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopPath parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopPath parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopPath parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopPath prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopPathOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.opera.core.systems.scope.protos.DesktopUtilsProtos.internal_static_scope_DesktopPath_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.opera.core.systems.scope.protos.DesktopUtilsProtos.internal_static_scope_DesktopPath_fieldAccessorTable;
      }
      
      // Construct using com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopPath.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        path_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopPath.getDescriptor();
      }
      
      public com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopPath getDefaultInstanceForType() {
        return com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopPath.getDefaultInstance();
      }
      
      public com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopPath build() {
        com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopPath result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopPath buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopPath result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopPath buildPartial() {
        com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopPath result = new com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopPath(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.path_ = path_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopPath) {
          return mergeFrom((com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopPath)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopPath other) {
        if (other == com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopPath.getDefaultInstance()) return this;
        if (other.hasPath()) {
          setPath(other.getPath());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasPath()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              path_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string path = 1;
      private java.lang.Object path_ = "";
      public boolean hasPath() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getPath() {
        java.lang.Object ref = path_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          path_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPath(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        path_ = value;
        onChanged();
        return this;
      }
      public Builder clearPath() {
        bitField0_ = (bitField0_ & ~0x00000001);
        path_ = getDefaultInstance().getPath();
        onChanged();
        return this;
      }
      void setPath(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        path_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:scope.DesktopPath)
    }
    
    static {
      defaultInstance = new DesktopPath(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:scope.DesktopPath)
  }
  
  public interface DesktopPidOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required uint32 pid = 1;
    boolean hasPid();
    int getPid();
  }
  public static final class DesktopPid extends
      com.google.protobuf.GeneratedMessage
      implements DesktopPidOrBuilder {
    // Use DesktopPid.newBuilder() to construct.
    private DesktopPid(Builder builder) {
      super(builder);
    }
    private DesktopPid(boolean noInit) {}
    
    private static final DesktopPid defaultInstance;
    public static DesktopPid getDefaultInstance() {
      return defaultInstance;
    }
    
    public DesktopPid getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.opera.core.systems.scope.protos.DesktopUtilsProtos.internal_static_scope_DesktopPid_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.opera.core.systems.scope.protos.DesktopUtilsProtos.internal_static_scope_DesktopPid_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required uint32 pid = 1;
    public static final int PID_FIELD_NUMBER = 1;
    private int pid_;
    public boolean hasPid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getPid() {
      return pid_;
    }
    
    private void initFields() {
      pid_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasPid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, pid_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, pid_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopPid parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopPid parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopPid parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopPid parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopPid parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopPid parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopPid parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopPid parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopPid parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopPid parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopPid prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopPidOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.opera.core.systems.scope.protos.DesktopUtilsProtos.internal_static_scope_DesktopPid_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.opera.core.systems.scope.protos.DesktopUtilsProtos.internal_static_scope_DesktopPid_fieldAccessorTable;
      }
      
      // Construct using com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopPid.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        pid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopPid.getDescriptor();
      }
      
      public com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopPid getDefaultInstanceForType() {
        return com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopPid.getDefaultInstance();
      }
      
      public com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopPid build() {
        com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopPid result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopPid buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopPid result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopPid buildPartial() {
        com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopPid result = new com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopPid(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.pid_ = pid_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopPid) {
          return mergeFrom((com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopPid)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopPid other) {
        if (other == com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopPid.getDefaultInstance()) return this;
        if (other.hasPid()) {
          setPid(other.getPid());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasPid()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              pid_ = input.readUInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required uint32 pid = 1;
      private int pid_ ;
      public boolean hasPid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getPid() {
        return pid_;
      }
      public Builder setPid(int value) {
        bitField0_ |= 0x00000001;
        pid_ = value;
        onChanged();
        return this;
      }
      public Builder clearPid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        pid_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:scope.DesktopPid)
    }
    
    static {
      defaultInstance = new DesktopPid(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:scope.DesktopPid)
  }
  
  public interface DesktopProductOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required uint32 productType = 1;
    boolean hasProductType();
    int getProductType();
    
    // required string labsProductName = 2;
    boolean hasLabsProductName();
    String getLabsProductName();
    
    // required string packageType = 3;
    boolean hasPackageType();
    String getPackageType();
  }
  public static final class DesktopProduct extends
      com.google.protobuf.GeneratedMessage
      implements DesktopProductOrBuilder {
    // Use DesktopProduct.newBuilder() to construct.
    private DesktopProduct(Builder builder) {
      super(builder);
    }
    private DesktopProduct(boolean noInit) {}
    
    private static final DesktopProduct defaultInstance;
    public static DesktopProduct getDefaultInstance() {
      return defaultInstance;
    }
    
    public DesktopProduct getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.opera.core.systems.scope.protos.DesktopUtilsProtos.internal_static_scope_DesktopProduct_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.opera.core.systems.scope.protos.DesktopUtilsProtos.internal_static_scope_DesktopProduct_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required uint32 productType = 1;
    public static final int PRODUCTTYPE_FIELD_NUMBER = 1;
    private int productType_;
    public boolean hasProductType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getProductType() {
      return productType_;
    }
    
    // required string labsProductName = 2;
    public static final int LABSPRODUCTNAME_FIELD_NUMBER = 2;
    private java.lang.Object labsProductName_;
    public boolean hasLabsProductName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getLabsProductName() {
      java.lang.Object ref = labsProductName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          labsProductName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getLabsProductNameBytes() {
      java.lang.Object ref = labsProductName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        labsProductName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string packageType = 3;
    public static final int PACKAGETYPE_FIELD_NUMBER = 3;
    private java.lang.Object packageType_;
    public boolean hasPackageType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getPackageType() {
      java.lang.Object ref = packageType_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          packageType_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPackageTypeBytes() {
      java.lang.Object ref = packageType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        packageType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      productType_ = 0;
      labsProductName_ = "";
      packageType_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasProductType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLabsProductName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPackageType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, productType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getLabsProductNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getPackageTypeBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, productType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getLabsProductNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getPackageTypeBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopProduct parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopProduct parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopProduct parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopProduct parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopProduct parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopProduct parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopProduct parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopProduct parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopProduct parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopProduct parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopProduct prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopProductOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.opera.core.systems.scope.protos.DesktopUtilsProtos.internal_static_scope_DesktopProduct_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.opera.core.systems.scope.protos.DesktopUtilsProtos.internal_static_scope_DesktopProduct_fieldAccessorTable;
      }
      
      // Construct using com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopProduct.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        productType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        labsProductName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        packageType_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopProduct.getDescriptor();
      }
      
      public com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopProduct getDefaultInstanceForType() {
        return com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopProduct.getDefaultInstance();
      }
      
      public com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopProduct build() {
        com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopProduct result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopProduct buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopProduct result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopProduct buildPartial() {
        com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopProduct result = new com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopProduct(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.productType_ = productType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.labsProductName_ = labsProductName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.packageType_ = packageType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopProduct) {
          return mergeFrom((com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopProduct)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopProduct other) {
        if (other == com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopProduct.getDefaultInstance()) return this;
        if (other.hasProductType()) {
          setProductType(other.getProductType());
        }
        if (other.hasLabsProductName()) {
          setLabsProductName(other.getLabsProductName());
        }
        if (other.hasPackageType()) {
          setPackageType(other.getPackageType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasProductType()) {
          
          return false;
        }
        if (!hasLabsProductName()) {
          
          return false;
        }
        if (!hasPackageType()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              productType_ = input.readUInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              labsProductName_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              packageType_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required uint32 productType = 1;
      private int productType_ ;
      public boolean hasProductType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getProductType() {
        return productType_;
      }
      public Builder setProductType(int value) {
        bitField0_ |= 0x00000001;
        productType_ = value;
        onChanged();
        return this;
      }
      public Builder clearProductType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        productType_ = 0;
        onChanged();
        return this;
      }
      
      // required string labsProductName = 2;
      private java.lang.Object labsProductName_ = "";
      public boolean hasLabsProductName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getLabsProductName() {
        java.lang.Object ref = labsProductName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          labsProductName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setLabsProductName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        labsProductName_ = value;
        onChanged();
        return this;
      }
      public Builder clearLabsProductName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        labsProductName_ = getDefaultInstance().getLabsProductName();
        onChanged();
        return this;
      }
      void setLabsProductName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        labsProductName_ = value;
        onChanged();
      }
      
      // required string packageType = 3;
      private java.lang.Object packageType_ = "";
      public boolean hasPackageType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getPackageType() {
        java.lang.Object ref = packageType_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          packageType_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPackageType(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        packageType_ = value;
        onChanged();
        return this;
      }
      public Builder clearPackageType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        packageType_ = getDefaultInstance().getPackageType();
        onChanged();
        return this;
      }
      void setPackageType(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        packageType_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:scope.DesktopProduct)
    }
    
    static {
      defaultInstance = new DesktopProduct(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:scope.DesktopProduct)
  }
  
  public interface DesktopVersionOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required uint32 majorVer = 1;
    boolean hasMajorVer();
    int getMajorVer();
    
    // required uint32 minorVer = 2;
    boolean hasMinorVer();
    int getMinorVer();
    
    // required uint32 buildNo = 3;
    boolean hasBuildNo();
    int getBuildNo();
  }
  public static final class DesktopVersion extends
      com.google.protobuf.GeneratedMessage
      implements DesktopVersionOrBuilder {
    // Use DesktopVersion.newBuilder() to construct.
    private DesktopVersion(Builder builder) {
      super(builder);
    }
    private DesktopVersion(boolean noInit) {}
    
    private static final DesktopVersion defaultInstance;
    public static DesktopVersion getDefaultInstance() {
      return defaultInstance;
    }
    
    public DesktopVersion getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.opera.core.systems.scope.protos.DesktopUtilsProtos.internal_static_scope_DesktopVersion_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.opera.core.systems.scope.protos.DesktopUtilsProtos.internal_static_scope_DesktopVersion_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required uint32 majorVer = 1;
    public static final int MAJORVER_FIELD_NUMBER = 1;
    private int majorVer_;
    public boolean hasMajorVer() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getMajorVer() {
      return majorVer_;
    }
    
    // required uint32 minorVer = 2;
    public static final int MINORVER_FIELD_NUMBER = 2;
    private int minorVer_;
    public boolean hasMinorVer() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getMinorVer() {
      return minorVer_;
    }
    
    // required uint32 buildNo = 3;
    public static final int BUILDNO_FIELD_NUMBER = 3;
    private int buildNo_;
    public boolean hasBuildNo() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getBuildNo() {
      return buildNo_;
    }
    
    private void initFields() {
      majorVer_ = 0;
      minorVer_ = 0;
      buildNo_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasMajorVer()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMinorVer()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBuildNo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, majorVer_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, minorVer_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(3, buildNo_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, majorVer_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, minorVer_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, buildNo_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopVersion parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopVersion parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopVersion parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopVersion parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopVersion parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopVersion parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopVersion parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopVersion parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopVersion parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopVersion parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopVersion prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopVersionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.opera.core.systems.scope.protos.DesktopUtilsProtos.internal_static_scope_DesktopVersion_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.opera.core.systems.scope.protos.DesktopUtilsProtos.internal_static_scope_DesktopVersion_fieldAccessorTable;
      }
      
      // Construct using com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopVersion.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        majorVer_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        minorVer_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        buildNo_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopVersion.getDescriptor();
      }
      
      public com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopVersion getDefaultInstanceForType() {
        return com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopVersion.getDefaultInstance();
      }
      
      public com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopVersion build() {
        com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopVersion result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopVersion buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopVersion result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopVersion buildPartial() {
        com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopVersion result = new com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopVersion(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.majorVer_ = majorVer_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.minorVer_ = minorVer_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.buildNo_ = buildNo_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopVersion) {
          return mergeFrom((com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopVersion)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopVersion other) {
        if (other == com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopVersion.getDefaultInstance()) return this;
        if (other.hasMajorVer()) {
          setMajorVer(other.getMajorVer());
        }
        if (other.hasMinorVer()) {
          setMinorVer(other.getMinorVer());
        }
        if (other.hasBuildNo()) {
          setBuildNo(other.getBuildNo());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasMajorVer()) {
          
          return false;
        }
        if (!hasMinorVer()) {
          
          return false;
        }
        if (!hasBuildNo()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              majorVer_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              minorVer_ = input.readUInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              buildNo_ = input.readUInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required uint32 majorVer = 1;
      private int majorVer_ ;
      public boolean hasMajorVer() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getMajorVer() {
        return majorVer_;
      }
      public Builder setMajorVer(int value) {
        bitField0_ |= 0x00000001;
        majorVer_ = value;
        onChanged();
        return this;
      }
      public Builder clearMajorVer() {
        bitField0_ = (bitField0_ & ~0x00000001);
        majorVer_ = 0;
        onChanged();
        return this;
      }
      
      // required uint32 minorVer = 2;
      private int minorVer_ ;
      public boolean hasMinorVer() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getMinorVer() {
        return minorVer_;
      }
      public Builder setMinorVer(int value) {
        bitField0_ |= 0x00000002;
        minorVer_ = value;
        onChanged();
        return this;
      }
      public Builder clearMinorVer() {
        bitField0_ = (bitField0_ & ~0x00000002);
        minorVer_ = 0;
        onChanged();
        return this;
      }
      
      // required uint32 buildNo = 3;
      private int buildNo_ ;
      public boolean hasBuildNo() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getBuildNo() {
        return buildNo_;
      }
      public Builder setBuildNo(int value) {
        bitField0_ |= 0x00000004;
        buildNo_ = value;
        onChanged();
        return this;
      }
      public Builder clearBuildNo() {
        bitField0_ = (bitField0_ & ~0x00000004);
        buildNo_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:scope.DesktopVersion)
    }
    
    static {
      defaultInstance = new DesktopVersion(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:scope.DesktopVersion)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_scope_DesktopStringID_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_scope_DesktopStringID_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_scope_DesktopStringText_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_scope_DesktopStringText_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_scope_DesktopPath_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_scope_DesktopPath_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_scope_DesktopPid_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_scope_DesktopPid_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_scope_DesktopProduct_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_scope_DesktopProduct_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_scope_DesktopVersion_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_scope_DesktopVersion_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ntemp.proto\022\005scope\"#\n\017DesktopStringID\022\020" +
      "\n\010enumText\030\001 \002(\t\"!\n\021DesktopStringText\022\014\n" +
      "\004text\030\001 \002(\t\"\033\n\013DesktopPath\022\014\n\004path\030\001 \002(\t" +
      "\"\031\n\nDesktopPid\022\013\n\003pid\030\001 \002(\r\"S\n\016DesktopPr" +
      "oduct\022\023\n\013productType\030\001 \002(\r\022\027\n\017labsProduc" +
      "tName\030\002 \002(\t\022\023\n\013packageType\030\003 \002(\t\"E\n\016Desk" +
      "topVersion\022\020\n\010majorVer\030\001 \002(\r\022\020\n\010minorVer" +
      "\030\002 \002(\r\022\017\n\007buildNo\030\003 \002(\rB;\n#com.opera.cor" +
      "e.systems.scope.protosB\022DesktopUtilsProt" +
      "osH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_scope_DesktopStringID_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_scope_DesktopStringID_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_scope_DesktopStringID_descriptor,
              new java.lang.String[] { "EnumText", },
              com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopStringID.class,
              com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopStringID.Builder.class);
          internal_static_scope_DesktopStringText_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_scope_DesktopStringText_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_scope_DesktopStringText_descriptor,
              new java.lang.String[] { "Text", },
              com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopStringText.class,
              com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopStringText.Builder.class);
          internal_static_scope_DesktopPath_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_scope_DesktopPath_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_scope_DesktopPath_descriptor,
              new java.lang.String[] { "Path", },
              com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopPath.class,
              com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopPath.Builder.class);
          internal_static_scope_DesktopPid_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_scope_DesktopPid_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_scope_DesktopPid_descriptor,
              new java.lang.String[] { "Pid", },
              com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopPid.class,
              com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopPid.Builder.class);
          internal_static_scope_DesktopProduct_descriptor =
            getDescriptor().getMessageTypes().get(4);
          internal_static_scope_DesktopProduct_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_scope_DesktopProduct_descriptor,
              new java.lang.String[] { "ProductType", "LabsProductName", "PackageType", },
              com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopProduct.class,
              com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopProduct.Builder.class);
          internal_static_scope_DesktopVersion_descriptor =
            getDescriptor().getMessageTypes().get(5);
          internal_static_scope_DesktopVersion_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_scope_DesktopVersion_descriptor,
              new java.lang.String[] { "MajorVer", "MinorVer", "BuildNo", },
              com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopVersion.class,
              com.opera.core.systems.scope.protos.DesktopUtilsProtos.DesktopVersion.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
