// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: system_input.proto

package com.opera.core.systems.scope.protos;

public final class SystemInputProtos {
  private SystemInputProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum ModifierPressed
      implements com.google.protobuf.ProtocolMessageEnum {
    NONE(0, 0),
    CTRL(1, 1),
    SHIFT(2, 2),
    ALT(3, 4),
    META(4, 8),
    SUPER(5, 16),
    ;
    
    public static final int NONE_VALUE = 0;
    public static final int CTRL_VALUE = 1;
    public static final int SHIFT_VALUE = 2;
    public static final int ALT_VALUE = 4;
    public static final int META_VALUE = 8;
    public static final int SUPER_VALUE = 16;
    
    
    public final int getNumber() { return value; }
    
    public static ModifierPressed valueOf(int value) {
      switch (value) {
        case 0: return NONE;
        case 1: return CTRL;
        case 2: return SHIFT;
        case 4: return ALT;
        case 8: return META;
        case 16: return SUPER;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<ModifierPressed>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ModifierPressed>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ModifierPressed>() {
            public ModifierPressed findValueByNumber(int number) {
              return ModifierPressed.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.opera.core.systems.scope.protos.SystemInputProtos.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final ModifierPressed[] VALUES = {
      NONE, CTRL, SHIFT, ALT, META, SUPER, 
    };
    
    public static ModifierPressed valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private ModifierPressed(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:scope.ModifierPressed)
  }
  
  public interface MouseInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required uint32 x = 1;
    boolean hasX();
    int getX();
    
    // required uint32 y = 2;
    boolean hasY();
    int getY();
    
    // required .scope.MouseInfo.MouseButton button = 3;
    boolean hasButton();
    com.opera.core.systems.scope.protos.SystemInputProtos.MouseInfo.MouseButton getButton();
    
    // required uint32 numClicks = 4;
    boolean hasNumClicks();
    int getNumClicks();
    
    // required uint32 modifier = 5;
    boolean hasModifier();
    int getModifier();
  }
  public static final class MouseInfo extends
      com.google.protobuf.GeneratedMessage
      implements MouseInfoOrBuilder {
    // Use MouseInfo.newBuilder() to construct.
    private MouseInfo(Builder builder) {
      super(builder);
    }
    private MouseInfo(boolean noInit) {}
    
    private static final MouseInfo defaultInstance;
    public static MouseInfo getDefaultInstance() {
      return defaultInstance;
    }
    
    public MouseInfo getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.opera.core.systems.scope.protos.SystemInputProtos.internal_static_scope_MouseInfo_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.opera.core.systems.scope.protos.SystemInputProtos.internal_static_scope_MouseInfo_fieldAccessorTable;
    }
    
    public enum MouseButton
        implements com.google.protobuf.ProtocolMessageEnum {
      LEFT(0, 0),
      RIGHT(1, 1),
      MIDDLE(2, 2),
      ;
      
      public static final int LEFT_VALUE = 0;
      public static final int RIGHT_VALUE = 1;
      public static final int MIDDLE_VALUE = 2;
      
      
      public final int getNumber() { return value; }
      
      public static MouseButton valueOf(int value) {
        switch (value) {
          case 0: return LEFT;
          case 1: return RIGHT;
          case 2: return MIDDLE;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<MouseButton>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<MouseButton>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MouseButton>() {
              public MouseButton findValueByNumber(int number) {
                return MouseButton.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.opera.core.systems.scope.protos.SystemInputProtos.MouseInfo.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final MouseButton[] VALUES = {
        LEFT, RIGHT, MIDDLE, 
      };
      
      public static MouseButton valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private MouseButton(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:scope.MouseInfo.MouseButton)
    }
    
    private int bitField0_;
    // required uint32 x = 1;
    public static final int X_FIELD_NUMBER = 1;
    private int x_;
    public boolean hasX() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getX() {
      return x_;
    }
    
    // required uint32 y = 2;
    public static final int Y_FIELD_NUMBER = 2;
    private int y_;
    public boolean hasY() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getY() {
      return y_;
    }
    
    // required .scope.MouseInfo.MouseButton button = 3;
    public static final int BUTTON_FIELD_NUMBER = 3;
    private com.opera.core.systems.scope.protos.SystemInputProtos.MouseInfo.MouseButton button_;
    public boolean hasButton() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public com.opera.core.systems.scope.protos.SystemInputProtos.MouseInfo.MouseButton getButton() {
      return button_;
    }
    
    // required uint32 numClicks = 4;
    public static final int NUMCLICKS_FIELD_NUMBER = 4;
    private int numClicks_;
    public boolean hasNumClicks() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getNumClicks() {
      return numClicks_;
    }
    
    // required uint32 modifier = 5;
    public static final int MODIFIER_FIELD_NUMBER = 5;
    private int modifier_;
    public boolean hasModifier() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public int getModifier() {
      return modifier_;
    }
    
    private void initFields() {
      x_ = 0;
      y_ = 0;
      button_ = com.opera.core.systems.scope.protos.SystemInputProtos.MouseInfo.MouseButton.LEFT;
      numClicks_ = 0;
      modifier_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasX()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasY()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasButton()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNumClicks()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasModifier()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, x_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, y_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, button_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt32(4, numClicks_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeUInt32(5, modifier_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, x_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, y_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, button_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, numClicks_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, modifier_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.opera.core.systems.scope.protos.SystemInputProtos.MouseInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.opera.core.systems.scope.protos.SystemInputProtos.MouseInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.opera.core.systems.scope.protos.SystemInputProtos.MouseInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.opera.core.systems.scope.protos.SystemInputProtos.MouseInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.opera.core.systems.scope.protos.SystemInputProtos.MouseInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.opera.core.systems.scope.protos.SystemInputProtos.MouseInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.opera.core.systems.scope.protos.SystemInputProtos.MouseInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.opera.core.systems.scope.protos.SystemInputProtos.MouseInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.opera.core.systems.scope.protos.SystemInputProtos.MouseInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.opera.core.systems.scope.protos.SystemInputProtos.MouseInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.opera.core.systems.scope.protos.SystemInputProtos.MouseInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.opera.core.systems.scope.protos.SystemInputProtos.MouseInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.opera.core.systems.scope.protos.SystemInputProtos.internal_static_scope_MouseInfo_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.opera.core.systems.scope.protos.SystemInputProtos.internal_static_scope_MouseInfo_fieldAccessorTable;
      }
      
      // Construct using com.opera.core.systems.scope.protos.SystemInputProtos.MouseInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        x_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        y_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        button_ = com.opera.core.systems.scope.protos.SystemInputProtos.MouseInfo.MouseButton.LEFT;
        bitField0_ = (bitField0_ & ~0x00000004);
        numClicks_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        modifier_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.opera.core.systems.scope.protos.SystemInputProtos.MouseInfo.getDescriptor();
      }
      
      public com.opera.core.systems.scope.protos.SystemInputProtos.MouseInfo getDefaultInstanceForType() {
        return com.opera.core.systems.scope.protos.SystemInputProtos.MouseInfo.getDefaultInstance();
      }
      
      public com.opera.core.systems.scope.protos.SystemInputProtos.MouseInfo build() {
        com.opera.core.systems.scope.protos.SystemInputProtos.MouseInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.opera.core.systems.scope.protos.SystemInputProtos.MouseInfo buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.opera.core.systems.scope.protos.SystemInputProtos.MouseInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.opera.core.systems.scope.protos.SystemInputProtos.MouseInfo buildPartial() {
        com.opera.core.systems.scope.protos.SystemInputProtos.MouseInfo result = new com.opera.core.systems.scope.protos.SystemInputProtos.MouseInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.x_ = x_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.y_ = y_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.button_ = button_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.numClicks_ = numClicks_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.modifier_ = modifier_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.opera.core.systems.scope.protos.SystemInputProtos.MouseInfo) {
          return mergeFrom((com.opera.core.systems.scope.protos.SystemInputProtos.MouseInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.opera.core.systems.scope.protos.SystemInputProtos.MouseInfo other) {
        if (other == com.opera.core.systems.scope.protos.SystemInputProtos.MouseInfo.getDefaultInstance()) return this;
        if (other.hasX()) {
          setX(other.getX());
        }
        if (other.hasY()) {
          setY(other.getY());
        }
        if (other.hasButton()) {
          setButton(other.getButton());
        }
        if (other.hasNumClicks()) {
          setNumClicks(other.getNumClicks());
        }
        if (other.hasModifier()) {
          setModifier(other.getModifier());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasX()) {
          
          return false;
        }
        if (!hasY()) {
          
          return false;
        }
        if (!hasButton()) {
          
          return false;
        }
        if (!hasNumClicks()) {
          
          return false;
        }
        if (!hasModifier()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              x_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              y_ = input.readUInt32();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              com.opera.core.systems.scope.protos.SystemInputProtos.MouseInfo.MouseButton value = com.opera.core.systems.scope.protos.SystemInputProtos.MouseInfo.MouseButton.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                button_ = value;
              }
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              numClicks_ = input.readUInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              modifier_ = input.readUInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required uint32 x = 1;
      private int x_ ;
      public boolean hasX() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getX() {
        return x_;
      }
      public Builder setX(int value) {
        bitField0_ |= 0x00000001;
        x_ = value;
        onChanged();
        return this;
      }
      public Builder clearX() {
        bitField0_ = (bitField0_ & ~0x00000001);
        x_ = 0;
        onChanged();
        return this;
      }
      
      // required uint32 y = 2;
      private int y_ ;
      public boolean hasY() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getY() {
        return y_;
      }
      public Builder setY(int value) {
        bitField0_ |= 0x00000002;
        y_ = value;
        onChanged();
        return this;
      }
      public Builder clearY() {
        bitField0_ = (bitField0_ & ~0x00000002);
        y_ = 0;
        onChanged();
        return this;
      }
      
      // required .scope.MouseInfo.MouseButton button = 3;
      private com.opera.core.systems.scope.protos.SystemInputProtos.MouseInfo.MouseButton button_ = com.opera.core.systems.scope.protos.SystemInputProtos.MouseInfo.MouseButton.LEFT;
      public boolean hasButton() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public com.opera.core.systems.scope.protos.SystemInputProtos.MouseInfo.MouseButton getButton() {
        return button_;
      }
      public Builder setButton(com.opera.core.systems.scope.protos.SystemInputProtos.MouseInfo.MouseButton value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        button_ = value;
        onChanged();
        return this;
      }
      public Builder clearButton() {
        bitField0_ = (bitField0_ & ~0x00000004);
        button_ = com.opera.core.systems.scope.protos.SystemInputProtos.MouseInfo.MouseButton.LEFT;
        onChanged();
        return this;
      }
      
      // required uint32 numClicks = 4;
      private int numClicks_ ;
      public boolean hasNumClicks() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getNumClicks() {
        return numClicks_;
      }
      public Builder setNumClicks(int value) {
        bitField0_ |= 0x00000008;
        numClicks_ = value;
        onChanged();
        return this;
      }
      public Builder clearNumClicks() {
        bitField0_ = (bitField0_ & ~0x00000008);
        numClicks_ = 0;
        onChanged();
        return this;
      }
      
      // required uint32 modifier = 5;
      private int modifier_ ;
      public boolean hasModifier() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public int getModifier() {
        return modifier_;
      }
      public Builder setModifier(int value) {
        bitField0_ |= 0x00000010;
        modifier_ = value;
        onChanged();
        return this;
      }
      public Builder clearModifier() {
        bitField0_ = (bitField0_ & ~0x00000010);
        modifier_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:scope.MouseInfo)
    }
    
    static {
      defaultInstance = new MouseInfo(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:scope.MouseInfo)
  }
  
  public interface KeyPressInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string key = 1;
    boolean hasKey();
    String getKey();
    
    // required uint32 modifier = 2;
    boolean hasModifier();
    int getModifier();
  }
  public static final class KeyPressInfo extends
      com.google.protobuf.GeneratedMessage
      implements KeyPressInfoOrBuilder {
    // Use KeyPressInfo.newBuilder() to construct.
    private KeyPressInfo(Builder builder) {
      super(builder);
    }
    private KeyPressInfo(boolean noInit) {}
    
    private static final KeyPressInfo defaultInstance;
    public static KeyPressInfo getDefaultInstance() {
      return defaultInstance;
    }
    
    public KeyPressInfo getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.opera.core.systems.scope.protos.SystemInputProtos.internal_static_scope_KeyPressInfo_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.opera.core.systems.scope.protos.SystemInputProtos.internal_static_scope_KeyPressInfo_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string key = 1;
    public static final int KEY_FIELD_NUMBER = 1;
    private java.lang.Object key_;
    public boolean hasKey() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          key_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required uint32 modifier = 2;
    public static final int MODIFIER_FIELD_NUMBER = 2;
    private int modifier_;
    public boolean hasModifier() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getModifier() {
      return modifier_;
    }
    
    private void initFields() {
      key_ = "";
      modifier_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasModifier()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getKeyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, modifier_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getKeyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, modifier_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.opera.core.systems.scope.protos.SystemInputProtos.KeyPressInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.opera.core.systems.scope.protos.SystemInputProtos.KeyPressInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.opera.core.systems.scope.protos.SystemInputProtos.KeyPressInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.opera.core.systems.scope.protos.SystemInputProtos.KeyPressInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.opera.core.systems.scope.protos.SystemInputProtos.KeyPressInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.opera.core.systems.scope.protos.SystemInputProtos.KeyPressInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.opera.core.systems.scope.protos.SystemInputProtos.KeyPressInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.opera.core.systems.scope.protos.SystemInputProtos.KeyPressInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.opera.core.systems.scope.protos.SystemInputProtos.KeyPressInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.opera.core.systems.scope.protos.SystemInputProtos.KeyPressInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.opera.core.systems.scope.protos.SystemInputProtos.KeyPressInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.opera.core.systems.scope.protos.SystemInputProtos.KeyPressInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.opera.core.systems.scope.protos.SystemInputProtos.internal_static_scope_KeyPressInfo_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.opera.core.systems.scope.protos.SystemInputProtos.internal_static_scope_KeyPressInfo_fieldAccessorTable;
      }
      
      // Construct using com.opera.core.systems.scope.protos.SystemInputProtos.KeyPressInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        key_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        modifier_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.opera.core.systems.scope.protos.SystemInputProtos.KeyPressInfo.getDescriptor();
      }
      
      public com.opera.core.systems.scope.protos.SystemInputProtos.KeyPressInfo getDefaultInstanceForType() {
        return com.opera.core.systems.scope.protos.SystemInputProtos.KeyPressInfo.getDefaultInstance();
      }
      
      public com.opera.core.systems.scope.protos.SystemInputProtos.KeyPressInfo build() {
        com.opera.core.systems.scope.protos.SystemInputProtos.KeyPressInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.opera.core.systems.scope.protos.SystemInputProtos.KeyPressInfo buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.opera.core.systems.scope.protos.SystemInputProtos.KeyPressInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.opera.core.systems.scope.protos.SystemInputProtos.KeyPressInfo buildPartial() {
        com.opera.core.systems.scope.protos.SystemInputProtos.KeyPressInfo result = new com.opera.core.systems.scope.protos.SystemInputProtos.KeyPressInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.key_ = key_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.modifier_ = modifier_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.opera.core.systems.scope.protos.SystemInputProtos.KeyPressInfo) {
          return mergeFrom((com.opera.core.systems.scope.protos.SystemInputProtos.KeyPressInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.opera.core.systems.scope.protos.SystemInputProtos.KeyPressInfo other) {
        if (other == com.opera.core.systems.scope.protos.SystemInputProtos.KeyPressInfo.getDefaultInstance()) return this;
        if (other.hasKey()) {
          setKey(other.getKey());
        }
        if (other.hasModifier()) {
          setModifier(other.getModifier());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasKey()) {
          
          return false;
        }
        if (!hasModifier()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              key_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              modifier_ = input.readUInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string key = 1;
      private java.lang.Object key_ = "";
      public boolean hasKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          key_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setKey(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
        return this;
      }
      public Builder clearKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      void setKey(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
      }
      
      // required uint32 modifier = 2;
      private int modifier_ ;
      public boolean hasModifier() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getModifier() {
        return modifier_;
      }
      public Builder setModifier(int value) {
        bitField0_ |= 0x00000002;
        modifier_ = value;
        onChanged();
        return this;
      }
      public Builder clearModifier() {
        bitField0_ = (bitField0_ & ~0x00000002);
        modifier_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:scope.KeyPressInfo)
    }
    
    static {
      defaultInstance = new KeyPressInfo(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:scope.KeyPressInfo)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_scope_MouseInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_scope_MouseInfo_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_scope_KeyPressInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_scope_KeyPressInfo_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022system_input.proto\022\005scope\032\"opera/scope" +
      "/scope_descriptor.proto\"\244\001\n\tMouseInfo\022\t\n" +
      "\001x\030\001 \002(\r\022\t\n\001y\030\002 \002(\r\022,\n\006button\030\003 \002(\0162\034.sc" +
      "ope.MouseInfo.MouseButton\022\021\n\tnumClicks\030\004" +
      " \002(\r\022\020\n\010modifier\030\005 \002(\r\".\n\013MouseButton\022\010\n" +
      "\004LEFT\020\000\022\t\n\005RIGHT\020\001\022\n\n\006MIDDLE\020\002\"-\n\014KeyPre" +
      "ssInfo\022\013\n\003key\030\001 \002(\t\022\020\n\010modifier\030\002 \002(\r*N\n" +
      "\017ModifierPressed\022\010\n\004NONE\020\000\022\010\n\004CTRL\020\001\022\t\n\005" +
      "SHIFT\020\002\022\007\n\003ALT\020\004\022\010\n\004META\020\010\022\t\n\005SUPER\020\020B:\n" +
      "#com.opera.core.systems.scope.protosB\021Sy",
      "stemInputProtosH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_scope_MouseInfo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_scope_MouseInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_scope_MouseInfo_descriptor,
              new java.lang.String[] { "X", "Y", "Button", "NumClicks", "Modifier", },
              com.opera.core.systems.scope.protos.SystemInputProtos.MouseInfo.class,
              com.opera.core.systems.scope.protos.SystemInputProtos.MouseInfo.Builder.class);
          internal_static_scope_KeyPressInfo_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_scope_KeyPressInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_scope_KeyPressInfo_descriptor,
              new java.lang.String[] { "Key", "Modifier", },
              com.opera.core.systems.scope.protos.SystemInputProtos.KeyPressInfo.class,
              com.opera.core.systems.scope.protos.SystemInputProtos.KeyPressInfo.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ScopeDescriptor.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
