//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.11 at 10:36:39 AM CET 
//


package com.opera.core.systems.scope.beans;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.opera.core.systems.scope.beans package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _HighGreen_QNAME = new QName("", "high-green");
    private final static QName _PrototypeId_QNAME = new QName("", "prototype-id");
    private final static QName _Count_QNAME = new QName("", "count");
    private final static QName _Keyup_QNAME = new QName("", "keyup");
    private final static QName _Tag_QNAME = new QName("", "tag");
    private final static QName _PropertyName_QNAME = new QName("", "property-name");
    private final static QName _ClassName_QNAME = new QName("", "class-name");
    private final static QName _Iscallable_QNAME = new QName("", "iscallable");
    private final static QName _ScriptData_QNAME = new QName("", "script-data");
    private final static QName _Description_QNAME = new QName("", "description");
    private final static QName _FunctionName_QNAME = new QName("", "function-name");
    private final static QName _RuntimeId_QNAME = new QName("", "runtime-id");
    private final static QName _Base64EncodedData_QNAME = new QName("", "base64-encoded-data");
    private final static QName _Status_QNAME = new QName("", "status");
    private final static QName _HighBlue_QNAME = new QName("", "high-blue");
    private final static QName _Keydown_QNAME = new QName("", "keydown");
    private final static QName _Property_QNAME = new QName("", "property");
    private final static QName _FrameId_QNAME = new QName("", "frame-id");
    private final static QName _Uri_QNAME = new QName("", "uri");
    private final static QName _Header_QNAME = new QName("", "header");
    private final static QName _Include_QNAME = new QName("", "include");
    private final static QName _StopType_QNAME = new QName("", "stop-type");
    private final static QName _Window_QNAME = new QName("", "window");
    private final static QName _DataType_QNAME = new QName("", "data-type");
    private final static QName _HighRed_QNAME = new QName("", "high-red");
    private final static QName _Param_QNAME = new QName("", "param");
    private final static QName _ObjectValue_QNAME = new QName("", "object-value");
    private final static QName _HtmlFramePath_QNAME = new QName("", "html-frame-path");
    private final static QName _RequestId_QNAME = new QName("", "request-id");
    private final static QName _Runtime_QNAME = new QName("", "runtime");
    private final static QName _Id_QNAME = new QName("", "id");
    private final static QName _ThreadId_QNAME = new QName("", "thread-id");
    private final static QName _LowRed_QNAME = new QName("", "low-red");
    private final static QName _Title_QNAME = new QName("", "title");
    private final static QName _ValueData_QNAME = new QName("", "value-data");
    private final static QName _Name_QNAME = new QName("", "name");
    private final static QName _WindowType_QNAME = new QName("", "window-type");
    private final static QName _WindowId_QNAME = new QName("", "window-id");
    private final static QName _LowGreen_QNAME = new QName("", "low-green");
    private final static QName _OpenerId_QNAME = new QName("", "opener-id");
    private final static QName _Severity_QNAME = new QName("", "severity");
    private final static QName _Buttons_QNAME = new QName("", "buttons");
    private final static QName _Exclude_QNAME = new QName("", "exclude");
    private final static QName _LowBlue_QNAME = new QName("", "low-blue");
    private final static QName _ObjectId_QNAME = new QName("", "object-id");
    private final static QName _H_QNAME = new QName("", "h");
    private final static QName _Isfunction_QNAME = new QName("", "isfunction");
    private final static QName _W_QNAME = new QName("", "w");
    private final static QName _Source_QNAME = new QName("", "source");
    private final static QName _Png_QNAME = new QName("", "png");
    private final static QName _Context_QNAME = new QName("", "context");
    private final static QName _Md5_QNAME = new QName("", "md5");
    private final static QName _Timeout_QNAME = new QName("", "timeout");
    private final static QName _Y_QNAME = new QName("", "y");
    private final static QName _X_QNAME = new QName("", "x");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.opera.core.systems.scope.beans
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link IncludeImage }
     * 
     */
    public IncludeImage createIncludeImage() {
        return new IncludeImage();
    }

    /**
     * Create an instance of {@link ColorSpec }
     * 
     */
    public ColorSpec createColorSpec() {
        return new ColorSpec();
    }

    /**
     * Create an instance of {@link NotOpened }
     * 
     */
    public NotOpened createNotOpened() {
        return new NotOpened();
    }

    /**
     * Create an instance of {@link Exec }
     * 
     */
    public Exec createExec() {
        return new Exec();
    }

    /**
     * Create an instance of {@link CreateAllRuntimes }
     * 
     */
    public CreateAllRuntimes createCreateAllRuntimes() {
        return new CreateAllRuntimes();
    }

    /**
     * Create an instance of {@link MouseAction }
     * 
     */
    public MouseAction createMouseAction() {
        return new MouseAction();
    }

    /**
     * Create an instance of {@link Pattern }
     * 
     */
    public Pattern createPattern() {
        return new Pattern();
    }

    /**
     * Create an instance of {@link Text }
     * 
     */
    public Text createText() {
        return new Text();
    }

    /**
     * Create an instance of {@link ValueData }
     * 
     */
    public ValueData createValueData() {
        return new ValueData();
    }

    /**
     * Create an instance of {@link Window }
     * 
     */
    public Window createWindow() {
        return new Window();
    }

    /**
     * Create an instance of {@link HtmlObject }
     * 
     */
    public HtmlObject createObject() {
        return new HtmlObject();
    }

    /**
     * Create an instance of {@link WindowClosed }
     * 
     */
    public WindowClosed createWindowClosed() {
        return new WindowClosed();
    }

    /**
     * Create an instance of {@link Request }
     * 
     */
    public Request createRequest() {
        return new Request();
    }

    /**
     * Create an instance of {@link HttpResponse }
     * 
     */
    public HttpResponse createResponse() {
        return new HttpResponse();
    }

    /**
     * Create an instance of {@link Area }
     * 
     */
    public Area createArea() {
        return new Area();
    }

    /**
     * Create an instance of {@link Type }
     * 
     */
    public Type createType() {
        return new Type();
    }

    /**
     * Create an instance of {@link RuntimeStarted }
     * 
     */
    public RuntimeStarted createRuntimeStarted() {
        return new RuntimeStarted();
    }

    /**
     * Create an instance of {@link ViewportRelative }
     * 
     */
    public ViewportRelative createViewportRelative() {
        return new ViewportRelative();
    }

    /**
     * Create an instance of {@link Runtimes }
     * 
     */
    public Runtimes createRuntimes() {
        return new Runtimes();
    }

    /**
     * Create an instance of {@link ActionInfoList }
     * 
     */
    public ActionInfoList createActionInfoList() {
        return new ActionInfoList();
    }

    /**
     * Create an instance of {@link No }
     * 
     */
    public No createNo() {
        return new No();
    }

    /**
     * Create an instance of {@link ObjectValue }
     * 
     */
    public ObjectValue createObjectValue() {
        return new ObjectValue();
    }

    /**
     * Create an instance of {@link Runtime }
     * 
     */
    public Runtime createRuntime() {
        return new Runtime();
    }

    /**
     * Create an instance of {@link EvalReply }
     * 
     */
    public EvalReply createEvalReply() {
        return new EvalReply();
    }

    /**
     * Create an instance of {@link Clear }
     * 
     */
    public Clear createClear() {
        return new Clear();
    }

    /**
     * Create an instance of {@link RuntimesReply }
     * 
     */
    public RuntimesReply createRuntimesReply() {
        return new RuntimesReply();
    }

    /**
     * Create an instance of {@link ExamineObjects }
     * 
     */
    public ExamineObjects createExamineObjects() {
        return new ExamineObjects();
    }

    /**
     * Create an instance of {@link Action }
     * 
     */
    public Action createAction() {
        return new Action();
    }

    /**
     * Create an instance of {@link UpdatedWindow }
     * 
     */
    public UpdatedWindow createUpdatedWindow() {
        return new UpdatedWindow();
    }

    /**
     * Create an instance of {@link Yes }
     * 
     */
    public Yes createYes() {
        return new Yes();
    }

    /**
     * Create an instance of {@link RuntimeStopped }
     * 
     */
    public RuntimeStopped createRuntimeStopped() {
        return new RuntimeStopped();
    }

    /**
     * Create an instance of {@link ObjectAttributes }
     * 
     */
    public ObjectAttributes createObjectAttributes() {
        return new ObjectAttributes();
    }

    /**
     * Create an instance of {@link ListWindowsReply }
     * 
     */
    public ListWindowsReply createListWindowsReply() {
        return new ListWindowsReply();
    }

    /**
     * Create an instance of {@link ValueData.String }
     * 
     */
    public ValueData.String createValueDataString() {
        return new ValueData.String();
    }

    /**
     * Create an instance of {@link Filter }
     * 
     */
    public Filter createFilter() {
        return new Filter();
    }

    /**
     * Create an instance of {@link ColorMatch }
     * 
     */
    public ColorMatch createColorMatch() {
        return new ColorMatch();
    }

    /**
     * Create an instance of {@link ExamineReply }
     * 
     */
    public ExamineReply createExamineReply() {
        return new ExamineReply();
    }

    /**
     * Create an instance of {@link Property }
     * 
     */
    public Property createProperty() {
        return new Property();
    }

    /**
     * Create an instance of {@link Eval }
     * 
     */
    public Eval createEval() {
        return new Eval();
    }

    /**
     * Create an instance of {@link ScreenWatcher }
     * 
     */
    public ScreenWatcher createScreenWatcher() {
        return new ScreenWatcher();
    }

    /**
     * Create an instance of {@link SetConfiguration }
     * 
     */
    public SetConfiguration createSetConfiguration() {
        return new SetConfiguration();
    }

    /**
     * Create an instance of {@link ActiveWindow }
     * 
     */
    public ActiveWindow createActiveWindow() {
        return new ActiveWindow();
    }

    /**
     * Create an instance of {@link ScreenWatcherReply }
     * 
     */
    public ScreenWatcherReply createScreenWatcherReply() {
        return new ScreenWatcherReply();
    }

    /**
     * Create an instance of {@link StopAt }
     * 
     */
    public StopAt createStopAt() {
        return new StopAt();
    }

    /**
     * Create an instance of {@link Message }
     * 
     */
    public Message createMessage() {
        return new Message();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "high-green")
    public JAXBElement<Integer> createHighGreen(Integer value) {
        return new JAXBElement<Integer>(_HighGreen_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "prototype-id")
    public JAXBElement<Integer> createPrototypeId(Integer value) {
        return new JAXBElement<Integer>(_PrototypeId_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "count")
    public JAXBElement<Integer> createCount(Integer value) {
        return new JAXBElement<Integer>(_Count_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link java.lang.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "keyup")
    public JAXBElement<java.lang.String> createKeyup(java.lang.String value) {
        return new JAXBElement<java.lang.String>(_Keyup_QNAME, java.lang.String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "tag")
    public JAXBElement<Integer> createTag(Integer value) {
        return new JAXBElement<Integer>(_Tag_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link java.lang.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "property-name")
    public JAXBElement<java.lang.String> createPropertyName(java.lang.String value) {
        return new JAXBElement<java.lang.String>(_PropertyName_QNAME, java.lang.String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link java.lang.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "class-name")
    public JAXBElement<java.lang.String> createClassName(java.lang.String value) {
        return new JAXBElement<java.lang.String>(_ClassName_QNAME, java.lang.String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link java.lang.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "iscallable")
    public JAXBElement<java.lang.String> createIscallable(java.lang.String value) {
        return new JAXBElement<java.lang.String>(_Iscallable_QNAME, java.lang.String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link java.lang.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "script-data")
    public JAXBElement<java.lang.String> createScriptData(java.lang.String value) {
        return new JAXBElement<java.lang.String>(_ScriptData_QNAME, java.lang.String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Text }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "description")
    public JAXBElement<Text> createDescription(Text value) {
        return new JAXBElement<Text>(_Description_QNAME, Text.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link java.lang.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "function-name")
    public JAXBElement<java.lang.String> createFunctionName(java.lang.String value) {
        return new JAXBElement<java.lang.String>(_FunctionName_QNAME, java.lang.String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "runtime-id")
    public JAXBElement<Integer> createRuntimeId(Integer value) {
        return new JAXBElement<Integer>(_RuntimeId_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link java.lang.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "base64-encoded-data")
    public JAXBElement<java.lang.String> createBase64EncodedData(java.lang.String value) {
        return new JAXBElement<java.lang.String>(_Base64EncodedData_QNAME, java.lang.String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link java.lang.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "status")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<java.lang.String> createStatus(java.lang.String value) {
        return new JAXBElement<java.lang.String>(_Status_QNAME, java.lang.String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "high-blue")
    public JAXBElement<Integer> createHighBlue(Integer value) {
        return new JAXBElement<Integer>(_HighBlue_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link java.lang.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "keydown")
    public JAXBElement<java.lang.String> createKeydown(java.lang.String value) {
        return new JAXBElement<java.lang.String>(_Keydown_QNAME, java.lang.String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Property }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "property")
    public JAXBElement<Property> createProperty(Property value) {
        return new JAXBElement<Property>(_Property_QNAME, Property.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "frame-id")
    public JAXBElement<Integer> createFrameId(Integer value) {
        return new JAXBElement<Integer>(_FrameId_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link java.lang.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "uri")
    public JAXBElement<java.lang.String> createUri(java.lang.String value) {
        return new JAXBElement<java.lang.String>(_Uri_QNAME, java.lang.String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Text }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "header")
    public JAXBElement<Text> createHeader(Text value) {
        return new JAXBElement<Text>(_Header_QNAME, Text.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Pattern }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "include")
    public JAXBElement<Pattern> createInclude(Pattern value) {
        return new JAXBElement<Pattern>(_Include_QNAME, Pattern.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link java.lang.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "stop-type")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<java.lang.String> createStopType(java.lang.String value) {
        return new JAXBElement<java.lang.String>(_StopType_QNAME, java.lang.String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Window }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "window")
    public JAXBElement<Window> createWindow(Window value) {
        return new JAXBElement<Window>(_Window_QNAME, Window.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link java.lang.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "data-type")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<java.lang.String> createDataType(java.lang.String value) {
        return new JAXBElement<java.lang.String>(_DataType_QNAME, java.lang.String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "high-red")
    public JAXBElement<Integer> createHighRed(Integer value) {
        return new JAXBElement<Integer>(_HighRed_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link java.lang.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "param")
    public JAXBElement<java.lang.String> createParam(java.lang.String value) {
        return new JAXBElement<java.lang.String>(_Param_QNAME, java.lang.String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectValue }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "object-value")
    public JAXBElement<ObjectValue> createObjectValue(ObjectValue value) {
        return new JAXBElement<ObjectValue>(_ObjectValue_QNAME, ObjectValue.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link java.lang.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "html-frame-path")
    public JAXBElement<java.lang.String> createHtmlFramePath(java.lang.String value) {
        return new JAXBElement<java.lang.String>(_HtmlFramePath_QNAME, java.lang.String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "request-id")
    public JAXBElement<Integer> createRequestId(Integer value) {
        return new JAXBElement<Integer>(_RequestId_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Runtime }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "runtime")
    public JAXBElement<Runtime> createRuntime(Runtime value) {
        return new JAXBElement<Runtime>(_Runtime_QNAME, Runtime.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "id")
    public JAXBElement<Integer> createId(Integer value) {
        return new JAXBElement<Integer>(_Id_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "thread-id")
    public JAXBElement<Integer> createThreadId(Integer value) {
        return new JAXBElement<Integer>(_ThreadId_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "low-red")
    public JAXBElement<Integer> createLowRed(Integer value) {
        return new JAXBElement<Integer>(_LowRed_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Text }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "title")
    public JAXBElement<Text> createTitle(Text value) {
        return new JAXBElement<Text>(_Title_QNAME, Text.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValueData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "value-data")
    public JAXBElement<ValueData> createValueData(ValueData value) {
        return new JAXBElement<ValueData>(_ValueData_QNAME, ValueData.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link java.lang.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "name")
    public JAXBElement<java.lang.String> createName(java.lang.String value) {
        return new JAXBElement<java.lang.String>(_Name_QNAME, java.lang.String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link java.lang.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "window-type")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<java.lang.String> createWindowType(java.lang.String value) {
        return new JAXBElement<java.lang.String>(_WindowType_QNAME, java.lang.String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "window-id")
    public JAXBElement<Integer> createWindowId(Integer value) {
        return new JAXBElement<Integer>(_WindowId_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "low-green")
    public JAXBElement<Integer> createLowGreen(Integer value) {
        return new JAXBElement<Integer>(_LowGreen_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "opener-id")
    public JAXBElement<Integer> createOpenerId(Integer value) {
        return new JAXBElement<Integer>(_OpenerId_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link java.lang.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "severity")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<java.lang.String> createSeverity(java.lang.String value) {
        return new JAXBElement<java.lang.String>(_Severity_QNAME, java.lang.String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "buttons")
    public JAXBElement<Integer> createButtons(Integer value) {
        return new JAXBElement<Integer>(_Buttons_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Pattern }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "exclude")
    public JAXBElement<Pattern> createExclude(Pattern value) {
        return new JAXBElement<Pattern>(_Exclude_QNAME, Pattern.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "low-blue")
    public JAXBElement<Integer> createLowBlue(Integer value) {
        return new JAXBElement<Integer>(_LowBlue_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "object-id")
    public JAXBElement<Integer> createObjectId(Integer value) {
        return new JAXBElement<Integer>(_ObjectId_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "h")
    public JAXBElement<Integer> createH(Integer value) {
        return new JAXBElement<Integer>(_H_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link java.lang.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "isfunction")
    public JAXBElement<java.lang.String> createIsfunction(java.lang.String value) {
        return new JAXBElement<java.lang.String>(_Isfunction_QNAME, java.lang.String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "w")
    public JAXBElement<Integer> createW(Integer value) {
        return new JAXBElement<Integer>(_W_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link java.lang.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "source")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<java.lang.String> createSource(java.lang.String value) {
        return new JAXBElement<java.lang.String>(_Source_QNAME, java.lang.String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "png")
    public JAXBElement<byte[]> createPng(byte[] value) {
        return new JAXBElement<byte[]>(_Png_QNAME, byte[].class, null, ((byte[]) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Text }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "context")
    public JAXBElement<Text> createContext(Text value) {
        return new JAXBElement<Text>(_Context_QNAME, Text.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link java.lang.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "md5")
    public JAXBElement<java.lang.String> createMd5(java.lang.String value) {
        return new JAXBElement<java.lang.String>(_Md5_QNAME, java.lang.String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "timeout")
    public JAXBElement<Long> createTimeout(Long value) {
        return new JAXBElement<Long>(_Timeout_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "y")
    public JAXBElement<Integer> createY(Integer value) {
        return new JAXBElement<Integer>(_Y_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "x")
    public JAXBElement<Integer> createX(Integer value) {
        return new JAXBElement<Integer>(_X_QNAME, Integer.class, null, value);
    }

}
