//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.11 at 10:36:39 AM CET 
//


package com.opera.core.systems.scope.beans;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;sequence minOccurs="0">
 *           &lt;element ref="{}window-id"/>
 *           &lt;element ref="{}timeout"/>
 *           &lt;element ref="{}area"/>
 *         &lt;/sequence>
 *         &lt;element ref="{}md5" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}color-spec" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}include-image" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "windowId",
    "timeout",
    "area",
    "md5",
    "colorSpec",
    "includeImage"
})
@XmlRootElement(name = "screen-watcher")
public class ScreenWatcher {

    @XmlElement(name = "window-id")
    protected Integer windowId;
    protected Long timeout;
    protected Area area;
    protected List<String> md5;
    @XmlElement(name = "color-spec")
    protected List<ColorSpec> colorSpec;
    @XmlElement(name = "include-image")
    protected IncludeImage includeImage;

    /**
     * Gets the value of the windowId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getWindowId() {
        return windowId;
    }

    /**
     * Sets the value of the windowId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setWindowId(Integer value) {
        this.windowId = value;
    }

    /**
     * Gets the value of the timeout property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getTimeout() {
        return timeout;
    }

    /**
     * Sets the value of the timeout property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setTimeout(Long value) {
        this.timeout = value;
    }

    /**
     * Gets the value of the area property.
     * 
     * @return
     *     possible object is
     *     {@link Area }
     *     
     */
    public Area getArea() {
        return area;
    }

    /**
     * Sets the value of the area property.
     * 
     * @param value
     *     allowed object is
     *     {@link Area }
     *     
     */
    public void setArea(Area value) {
        this.area = value;
    }

    /**
     * Gets the value of the md5 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the md5 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMd5().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getMd5() {
        if (md5 == null) {
            md5 = new ArrayList<String>();
        }
        return this.md5;
    }

    /**
     * Gets the value of the colorSpec property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the colorSpec property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getColorSpec().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ColorSpec }
     * 
     * 
     */
    public List<ColorSpec> getColorSpec() {
        if (colorSpec == null) {
            colorSpec = new ArrayList<ColorSpec>();
        }
        return this.colorSpec;
    }

    /**
     * Gets the value of the includeImage property.
     * 
     * @return
     *     possible object is
     *     {@link IncludeImage }
     *     
     */
    public IncludeImage getIncludeImage() {
        return includeImage;
    }

    /**
     * Sets the value of the includeImage property.
     * 
     * @param value
     *     allowed object is
     *     {@link IncludeImage }
     *     
     */
    public void setIncludeImage(IncludeImage value) {
        this.includeImage = value;
    }

}
